---
title: "Birds in Mangnuson Park and Montlake Fill"
author: "Stephen Kaluzny"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("lubridate")
library("dplyr")
library("ggplot2")
```

# Introduction

# Data
From ebird.

Load the data for observations at Magnuson Park and the Montlake Fill.
This was extracted from the Washington state data using the ...
```{r data_MagnusonFill}
dMagnusonFill <- readRDS("dMagnusonAndFill.rds")
dim(dMagnusonFill)> dim(dMagnusonFill)
```

Find just ducks.
```{r data_ducks}
duckGenusDF <- read.csv("duckGenus.csv", stringsAsFactors=FALSE)
indxGenus <- unlist(lapply(duckGenusDF[, "Genus"],
  function(genus) grep(genus, dMagnusonFill[["scientific_name"]])))
ducksMagnusonFill <- dMagnusonFill[indxGenus,]
saveRDS(ducksMagnusonFill, "ducksMagnusonFill.rds")
```


# Ducks
```{r ducks_month}
ducksMagnusonFill %>%
	mutate(Month=month(observation_date), Year=year(observation_date)) %>%
	group_by(Month, Year, locality_id) %>%
	mutate(NDucks = n()) %>%
	ggplot(aes(Month, NDucks, color=as.factor(Year))) + geom_line() +
	  facet_grid(locality_id ~ .) +
      ggtitle("Ducks by Month")
```
